"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vre9XxzkB6X
 */
import { Button } from "@/components/ui/button"
import { DialogTrigger, DialogTitle, DialogDescription, DialogContent, Dialog } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"

import { StudentInfoSchema } from "@/types/zod-schemas"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import * as z from "zod"


export function AddStudentsDialog() {
  const form = useForm<z.infer<typeof StudentInfoSchema>>({
    resolver: zodResolver(StudentInfoSchema),
  })
  function onSubmit(values: z.infer<typeof StudentInfoSchema>) {
    // Do something with the form values.
    // ✅ This will be type-safe and validated.
    console.log(values)
  }

  return (
    <div className="max-w-sm space-y-2">
      <Dialog>
        <DialogTrigger>
          {/* <Button className="w-full">Add Student</Button> */}
          Add Student
        </DialogTrigger>
        <DialogContent className="space-y-2 overflow-y-auto max-h-[70vh]">
          <DialogTitle className="text-center text-3xl font-bold">
            Add Student
          </DialogTitle>
          <DialogDescription className="text-center text-gray-500 dark:text-gray-400">
            Enter student information
          </DialogDescription>
          <div className="space-y-4">
            
            {/* <div className="space-y-2">
              <Label htmlFor="registration_number">Registration Number</Label>
              <Input id="registration_number" {...register("registration_number")} placeholder="123456" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="student_contact_number">Contact Number</Label>
              <Input id="student_contact_number" {...register("student_contact_number")} placeholder="9822435463" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="student_email_address">Email Address</Label>
              <Input id="student_email_address" {...register("student_email_address")} placeholder="student@gmail.com" required type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="student_date_of_birth">Date of Birth</Label>
              <Input id="student_date_of_birth" {...register("student_date_of_birth")} required type="date" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="student_program">Program</Label>
              <Select {...register("student_program")} required>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select Program" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="B.Tech - Artificial Intelligence and Machine Learning">B.Tech - Artificial Intelligence and Machine Learning</SelectItem>
                  <SelectItem value="B.Tech - Computer Science">B.Tech - Computer Science</SelectItem>
                  <SelectItem value="B.Tech - Information Technology">B.Tech - Information Technology</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="department">Department</Label>
              <Select {...register("student_department")} required>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select Department" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Computer Science">Computer Science</SelectItem>
                  <SelectItem value="Electrical Engineering">Electrical Engineering</SelectItem>
                  <SelectItem value="Mechanical Engineering">Mechanical Engineering</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="department">Gender</Label>
              <Select {...register("student_gender")} required>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select Gender" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Male">Male</SelectItem>
                  <SelectItem value="Female">Female</SelectItem>
                  <SelectItem value="Other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="year">Year</Label>
              <Select {...register("student_academic_year")} required>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select Year" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="first">First</SelectItem>
                  <SelectItem value="Second">Second</SelectItem>
                  <SelectItem value="Third">Third</SelectItem>
                  <SelectItem value="Fourth">Fourth</SelectItem>
                </SelectContent>
              </Select>
            </div> */}

          </div>
        </DialogContent>
      </Dialog>
    </div >
  )
}