"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vre9XxzkB6X
 */
import { Button } from "@/components/ui/button"
import { DialogTrigger, DialogTitle, DialogDescription, DialogContent, Dialog } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { useForm, SubmitHandler } from "react-hook-form"

type FormValues = {
  first_name: string,
  last_name: string,
  registration_number: string,
  student_contact_number: string,
  student_email_address: string,
  student_date_of_birth: Date,
  student_program: string,
  student_department: string,
  student_gender: GenderEnum,
  student_academic_year: string,
}
enum GenderEnum {
  female = "female",
  male = "male",
  other = "other",
}


export function AddStudentsDialog() {
  const { register, handleSubmit, watch, formState: { errors } } = useForm<FormValues>();
  const onSubmit: SubmitHandler<FormValues> = (data) => console.log(data);
  return (
    <div className="max-w-sm space-y-2">
      <form onSubmit={handleSubmit(onSubmit)}>
        <Dialog>
        <DialogTrigger>
          {/* <Button className="w-full">Add Student</Button> */}
          Add Student
        </DialogTrigger>
        <DialogContent className="space-y-2 overflow-y-auto max-h-[70vh]">
          <DialogTitle className="text-center text-3xl font-bold">
            Add Student
          </DialogTitle>
          <DialogDescription className="text-center text-gray-500 dark:text-gray-400">
            Enter student information
          </DialogDescription>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="first_name">First name</Label>
                <Input id="first_name" {...register("first_name")} placeholder="Lee" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="last_name">Last name</Label>
                <Input id="last_name" {...register("last_name")} placeholder="Robinson" required />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="registration_number">Registration Number</Label>
              <Input id="registration_number" {...register("registration_number")} placeholder="123456" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="student_contact_number">Contact Number</Label>
              <Input id="student_contact_number" {...register("student_contact_number")} placeholder="9822435463" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="student_email_address">Email Address</Label>
              <Input id="student_email_address" {...register("student_email_address")} placeholder="student@gmail.com" required type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="student_date_of_birth">Date of Birth</Label>
              <Input id="student_date_of_birth" {...register("student_date_of_birth")} required type="date" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="student_program">Program</Label>
              <Select {...register("student_program")} required>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select Program" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="B.Tech - Artificial Intelligence and Machine Learning">B.Tech - Artificial Intelligence and Machine Learning</SelectItem>
                  <SelectItem value="B.Tech - Computer Science">B.Tech - Computer Science</SelectItem>
                  <SelectItem value="B.Tech - Information Technology">B.Tech - Information Technology</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="department">Department</Label>
              <Select {...register("student_department")} required>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select Department" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Computer Science">Computer Science</SelectItem>
                  <SelectItem value="Electrical Engineering">Electrical Engineering</SelectItem>
                  <SelectItem value="Mechanical Engineering">Mechanical Engineering</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="department">Gender</Label>
              <Select {...register("student_gender")} required>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select Gender" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Male">Male</SelectItem>
                  <SelectItem value="Female">Female</SelectItem>
                  <SelectItem value="Other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="year">Year</Label>
              <Select {...register("student_academic_year")} required>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select Year" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="first">First</SelectItem>
                  <SelectItem value="Second">Second</SelectItem>
                  <SelectItem value="Third">Third</SelectItem>
                  <SelectItem value="Fourth">Fourth</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button className="w-full" type="submit">
              Add Student
            </Button>
          </div>
        </DialogContent>
      </Dialog>
      </form>
    </div>
  )
}